### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by fcolista** [j0sh/crtmpserver#7]
I was maintaining crtmpserver for Alpine Linux.
But doesn't seems to me is still active.
Can you please confirm or unconfirm?
Thanks.

**Comment by pyite** [comment]
It sure appears to be stagnant.  Quite a shame, I just set this up and started using it.

I have a simple fix for the VLC "_checkbw" problem to contribute if this project ever comes back to life:

-        } else if (functionName == RM_INVOKE_FUNCTION_CHECKBANDWIDTH) {
+        } else if (functionName == RM_INVOKE_FUNCTION_CHECKBANDWIDTH || functionName == "_checkbw") {

**Comment by fcolista** [comment]
Does not seems to me that anybody is still interested in this project.
That's sad, since also the developers does not reply.
